export default function handler(req, res) {
  // Sample data from the provided JSON
  const users = [
    {
      "name": "J Vinod",
      "fathersName": "",
      "phoneNumber": "9490160194",
      "otherNumber": "",
      "passportNumber": "",
      "aadharNumber": "393933081942",
      "age": "28",
      "gender": "Male",
      "address": "Hyderabad",
      "district": "HYDERABAD",
      "pincode": "",
      "state": "TELANGANA",
      "town": ""
  },
  {
    "name": "J Vinod",
    "fathersName": "",
    "phoneNumber": "9490160194",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "393933081942",
    "age": "28",
    "gender": "Male",
    "address": "Hyderabad",
    "district": "HYDERABAD",
    "pincode": "",
    "state": "TELANGANA",
    "town": ""
  },
  {
    "Name": "RASHI",
    "Guardian Name": "",
    "Mobile No": "8295023718",
    "Aadhar No": "839332573101",
    "Age": "6",
    "Gender": "Female",
    "Address": "GPS DOHAR KALAN",
    "District": "MAHENDRAGARH",
    "Pincode": "",
    "State": "HARYANA",
    "Area": ""
  },
  {
    "Name": "A Venkataramana",
    "Guardian Name": "",
    "Mobile No": "9502021404",
    "Aadhar No": "714174105495",
    "Age": "70",
    "Gender": "Male",
    "Address": "Raju Vari Palli",
    "District": "CHITTOOR",
    "Pincode": "517234",
    "State": "ANDHRA PRADESH",
    "Area": "Kalikiri"
  },
  {
    "Name": "SNEHA",
    "Guardian Name": "",
    "Mobile No": "9813122094",
    "Aadhar No": "839403093262",
    "Age": "13",
    "Gender": "Female",
    "Address": "YADUVANSHI SCHOOL  SATNALI",
    "District": "MAHENDRAGARH",
    "Pincode": "",
    "State": "HARYANA",
    "Area": ""
  },
  {
    "Name": "Harshavardhan Kota",
    "Guardian Name": "",
    "Mobile No": "9666524547",
    "Aadhar No": "527583175307",
    "Age": "27",
    "Gender": "Male",
    "Address": "Nawab Peta",
    "District": "SPSR NELLORE",
    "Pincode": "524003",
    "State": "ANDHRA PRADESH",
    "Area": "Nellore"
  },
  {
    "Name": "Ab Rashid",
    "Guardian Name": "",
    "Mobile No": "9797156853",
    "Aadhar No": "410056561417",
    "Age": "48",
    "Gender": "Male",
    "Address": "Kawdara",
    "District": "SRINAGAR",
    "Pincode": "",
    "State": "JAMMU AND KASHMIR",
    "Area": ""
  },
  {
    "Name": "PRASANNA KUMAR BELKALE",
    "Guardian Name": "",
    "Mobile No": "9886096550",
    "Aadhar No": "221122730108",
    "Age": "42",
    "Gender": "Male",
    "Address": "804  BHARATH HOUSING CO OPERATIVE SOCIETY UTTARAHALLI 6TH CROSS KENGERI ROAD BANGALORE KARNATAKA",
    "District": "BENGALURU URBAN",
    "Pincode": "560061",
    "State": "KARNATAKA",
    "Area": ""
  },
  {
    "Name": "SAKSHI",
    "Guardian Name": "",
    "Mobile No": "7906721337",
    "Aadhar No": "669267455837",
    "Age": "21",
    "Gender": "Female",
    "Address": "LAXMIPUR  SAHASPUR  DEHRADUN",
    "District": "DEHRADUN",
    "Pincode": "248197",
    "State": "UTTARAKHAND",
    "Area": ""
  },
  {
    "Name": "B umadevi",
    "Guardian Name": "",
    "Mobile No": "9440112958",
    "Aadhar No": "804336844543",
    "Age": "46",
    "Gender": "Female",
    "Address": "Parlapadu",
    "District": "Y S R",
    "Pincode": "516359",
    "State": "ANDHRA PRADESH",
    "Area": "Rajupalem"
  },
  {
    "Name": "SMRITY",
    "Guardian Name": "",
    "Mobile No": "8210826876",
    "Aadhar No": "559045779779",
    "Age": "20",
    "Gender": "Female",
    "Address": "JAMAL PUR PATNA",
    "District": "DEHRADUN",
    "Pincode": "804454",
    "State": "UTTARAKHAND",
    "Area": ""
  },
  {
    "Name": "SHUBHAM UTTAKARSH",
    "Guardian Name": "",
    "Mobile No": "8013132610",
    "Aadhar No": "728136278764",
    "Age": "28",
    "Gender": "Male",
    "Address": "R-484  3RD FLOOR  PAMPOSH RD  NEW RAJINDER NAGAR - 110060  NEW DELHI  DELHI  110060",
    "District": "NEW DELHI",
    "Pincode": "110060",
    "State": "DELHI",
    "Area": ""
  },
  {
    "Name": "GEETA SHUKLA",
    "Guardian Name": "",
    "Mobile No": "7989927995",
    "Aadhar No": "786495408569",
    "Age": "57",
    "Gender": "Female",
    "Address": "E 8 JAYPEE NAGAR JAYPEE HITECH PLANT REWA",
    "District": "REWA",
    "Pincode": "486450",
    "State": "MADHYA PRADESH",
    "Area": ""
  },
  {
    "Name": "PATEL NISHI MAHESHBHAI",
    "Guardian Name": "",
    "Mobile No": "9054181743",
    "Aadhar No": "864623467560",
    "Age": "24",
    "Gender": "Female",
    "Address": "GURJAR SUTHAR NO MADH GHOSKOL DARVAJO VADNAGAR TA VADNAGAR",
    "District": "MAHESANA",
    "Pincode": "",
    "State": "GUJARAT",
    "Area": ""
  },
  {
    "Name": "Ms  SONU KOMBLE",
    "Guardian Name": "",
    "Mobile No": "9604756393",
    "Aadhar No": "694280288312",
    "Age": "36",
    "Gender": "Female",
    "Address": "nagpur maharashtra",
    "District": "NAGPUR",
    "Pincode": "",
    "State": "MAHARASHTRA",
    "Area": ""
  },
  {
    "Name": "Nikhil Waddar",
    "Guardian Name": "",
    "Mobile No": "7337786587",
    "Aadhar No": "543389229035",
    "Age": "18",
    "Gender": "Male",
    "Address": "HANMAPUR UMATAR HANAMAPUR  BELAGAUM",
    "District": "BELAGAVI",
    "Pincode": "591123",
    "State": "KARNATAKA",
    "Area": "Urban"
  },
  {
    "Name": "Mr  JULIA MUKHOPADHYAY",
    "Guardian Name": "",
    "Mobile No": "9963028526",
    "Aadhar No": "781150280602",
    "Age": "39",
    "Gender": "Male",
    "Address": "2208  BUILDING NO 7  HIGHLAND PARK  KOLSHET ROAD  DHOKALI  THANE  MAHARASHTRA - 400607",
    "District": "THANE",
    "Pincode": "400607",
    "State": "MAHARASHTRA",
    "Area": ""
  },
  {
    "Name": "SHUVENDU KONAI 82374",
    "Guardian Name": "",
    "Mobile No": "7602216241",
    "Aadhar No": "943731630492",
    "Age": "26",
    "Gender": "Male",
    "Address": "ANDHERI",
    "District": "MUMBAI",
    "Pincode": "400001",
    "State": "MAHARASHTRA",
    "Area": "Urban"
  },
  {
    "Name": "Ajay prabhakar chafe",
    "Guardian Name": "",
    "Mobile No": "8452885188",
    "Aadhar No": "685113044070",
    "Age": "32",
    "Gender": "Male",
    "Address": "Badlapur",
    "District": "THANE",
    "Pincode": "421503",
    "State": "MAHARASHTRA",
    "Area": "Rural"
  },
  {
    "Name": "MUNGREICHON RAISING",
    "Guardian Name": "Shailei Raising",
    "Mobile No": "8118903410",
    "Aadhar No": "822788748802",
    "Age": "25",
    "Gender": "Female",
    "Address": "IMPHAL  CHECKON  MANIPUR",
    "District": "IMPHAL EAST",
    "Pincode": "795142",
    "State": "MANIPUR",
    "Area": ""
  },
  {
    "Name": "Gannavarapu Sai Tulasi",
    "Guardian Name": "",
    "Mobile No": "9392223657",
    "Aadhar No": "998198787654",
    "Age": "21",
    "Gender": "Female",
    "Address": "Yandamuru",
    "District": "EAST GODAVARI",
    "Pincode": "533468",
    "State": "ANDHRA PRADESH",
    "Area": "Karapa"
  },
  {
    "Name": "Burugu Rangayya",
    "Guardian Name": "",
    "Mobile No": "9553972863",
    "Aadhar No": "341630483201",
    "Age": "35",
    "Gender": "Male",
    "Address": "Raipadu",
    "District": "VISAKHAPATANAM",
    "Pincode": "535145",
    "State": "ANDHRA PRADESH",
    "Area": "Ananthagiri"
  },
  {
    "Name": "PALASH BARMAN",
    "Guardian Name": "",
    "Mobile No": "8729839022",
    "Aadhar No": "805462061752",
    "Age": "26",
    "Gender": "Male",
    "Address": "MOHESKHALA TRIPURA",
    "District": "WEST TRIPURA",
    "Pincode": "799004",
    "State": "TRIPURA",
    "Area": ""
  },
  {
    "Name": "SHYAMU",
    "Guardian Name": "",
    "Mobile No": "8467018907",
    "Aadhar No": "288829532325",
    "Age": "17",
    "Gender": "Male",
    "Address": "CO SANT RO CHANDRASA KALAN KHERI U P",
    "District": "HARIDWAR",
    "Pincode": "",
    "State": "UTTARAKHAND",
    "Area": ""
  },
  {
    "Name": "MANIKANDAN",
    "Guardian Name": "",
    "Mobile No": "9894099233",
    "Aadhar No": "822156297668",
    "Age": "31",
    "Gender": "Male",
    "Address": "NARASIMMAN ROAD  ANNAMAR SAVADI SHEVAPET SALEM",
    "District": "SALEM",
    "Pincode": "636002",
    "State": "TAMIL NADU",
    "Area": "Urban"
  },
  {
    "Name": "A prathiba Rani",
    "Guardian Name": "",
    "Mobile No": "9133060780",
    "Aadhar No": "414078610576",
    "Age": "35",
    "Gender": "Female",
    "Address": "Vijayawada",
    "District": "KRISHNA",
    "Pincode": "520010",
    "State": "ANDHRA PRADESH",
    "Area": "Vijayawada"
  },
  {
    "Name": "SURESH D",
    "Guardian Name": "",
    "Mobile No": "8608344752",
    "Aadhar No": "272579566062",
    "Age": "30",
    "Gender": "Male",
    "Address": "2 SANSU AVENUE OLD PERUNGALATHUR",
    "District": "CHENGALPATTU",
    "Pincode": "600063",
    "State": "TAMIL NADU",
    "Area": ""
  },
  {
    "Name": "Ms  PRATIKSHA SAHARE",
    "Guardian Name": "",
    "Mobile No": "9337918740",
    "Aadhar No": "773186760536",
    "Age": "23",
    "Gender": "Female",
    "Address": "NAGPUR JARIPATKA 440 014",
    "District": "NAGPUR",
    "Pincode": "",
    "State": "MAHARASHTRA",
    "Area": ""
  },
  {
    "Name": "Mr  KURESHI JABBAR",
    "Guardian Name": "",
    "Mobile No": "9824280832",
    "Aadhar No": "273082766060",
    "Age": "46",
    "Gender": "Male",
    "Address": "BANDRA TERMINUS",
    "District": "MUMBAI",
    "Pincode": "",
    "State": "MAHARASHTRA",
    "Area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "CHANDRAVATHI",
    "fathersName": "",
    "phoneNumber": "9443129502",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "687548546061",
    "age": "29",
    "gender": "Female",
    "address": "D 0 BALACHANDRAN 6 PARASAKTHI ST POTHERI",
    "district": "CHENGALPATTU",
    "pincode": "603203",
    "state": "TAMIL NADU",
    "town": ""
  },
  {
    "name": "DIL BHADUR",
    "fathersName": "",
    "phoneNumber": "7060369827",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "826140371260",
    "age": "40",
    "gender": "Male",
    "address": "DLF LYNNDALF ESTATE MUSSOORIE",
    "district": "DEHRADUN",
    "pincode": "",
    "state": "UTTARAKHAND",
    "town": ""
  },
  {
    "name": "K Sarswathi",
    "fathersName": "",
    "phoneNumber": "8499958171",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "428346580855",
    "age": "23",
    "gender": "Female",
    "address": "Paidipadu",
    "district": "PRAKASAM",
    "pincode": "523271",
    "state": "ANDHRA PRADESH",
    "town": "Zarugumalli"
  },
  {
    "name": "Janapati Sujatha",
    "fathersName": "",
    "phoneNumber": "9848277347",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "673742610282",
    "age": "39",
    "gender": "Female",
    "address": "W o Ravi Gopalapuram",
    "district": "WEST GODAVARI",
    "pincode": "534316",
    "state": "ANDHRA PRADESH",
    "town": "Gopalapuram"
  },
  {
    "name": "KATHIRVELU",
    "fathersName": "",
    "phoneNumber": "9488567480",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "799000210409",
    "age": "76",
    "gender": "Male",
    "address": "NO-B1  VENGATESH NAGAR  GOUNDAMPALAYAM  CBE",
    "district": "COIMBATORE",
    "pincode": "641030",
    "state": "TAMIL NADU",
    "town": ""
  },
  {
    "name": "RASHIDA BANO",
    "fathersName": "",
    "phoneNumber": "9450000223",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "483789976234",
    "age": "60",
    "gender": "Female",
    "address": "349 PURANI DAAL MIL SAMA BIHAR COLONY NEAR AAI LUCKNOW",
    "district": "SOUTH EAST",
    "pincode": "",
    "state": "DELHI",
    "town": ""
  },
  {
    "name": "P Koteswari",
    "father_name": "",
    "mobile": "9949100591",
    "id_type": "",
    "id_number": "",
    "aadhar": "767290951654",
    "age": "35",
    "gender": "Female",
    "address": "Grempet",
    "district": "CHITTOOR",
    "pincode": "517502",
    "state": "ANDHRA PRADESH",
    "area": "Chittoor"
  },
  {
    "name": "ASHLESHA CHAVAN",
    "father_name": "",
    "mobile": "8766001514",
    "id_type": "",
    "id_number": "",
    "aadhar": "285063495109",
    "age": "19",
    "gender": "Female",
    "address": "PUNE MAHARASHTRA",
    "district": "PUNE",
    "pincode": "411001",
    "state": "MAHARASHTRA",
    "area": "Urban"
  },
  {
    "name": "BHUPALI ACHARYA",
    "father_name": "",
    "mobile": "9850815554",
    "id_type": "",
    "id_number": "",
    "aadhar": "868083734466",
    "age": "38",
    "gender": "Female",
    "address": "FLAT NO  6 BHAKTI PLAM NEAR SHRADDHATERECE SAMATA COLONYPIMPLE NILAKH PUNR PINCODE  4 1 1 0 2 7",
    "district": "PUNE",
    "pincode": "411027",
    "state": "MAHARASHTRA",
    "area": ""
  },
  {
    "name": "ANIL KUMAR KASAT",
    "father_name": "",
    "mobile": "8095969184",
    "id_type": "",
    "id_number": "",
    "aadhar": "907989514289",
    "age": "46",
    "gender": "Male",
    "address": "203 RELAIBAL LIFESTYLE LAYOUT HARLURU",
    "district": "BENGALURU URBAN",
    "pincode": "560102",
    "state": "KARNATAKA",
    "area": ""
  },
  {
    "name": "KONDLE SANTOSH MURLI",
    "father_name": "",
    "mobile": "6351373900",
    "id_type": "",
    "id_number": "",
    "aadhar": "993169512498",
    "age": "24",
    "gender": "Male",
    "address": "247 EKTA NAGAR  PARVAT GAAM  SURAT",
    "district": "SURAT",
    "pincode": "",
    "state": "GUJARAT",
    "area": ""
  },
  {
    "name": "RAM SWARUP",
    "father_name": "Sadiram",
    "mobile": "9680084033",
    "id_type": "",
    "id_number": "",
    "aadhar": "335108476074",
    "age": "66",
    "gender": "Male",
    "address": "GANPAT HOUSE NO 138 SHIKHOPUR 160 GURUGRAM",
    "district": "GURUGRAM",
    "pincode": "122004",
    "state": "HARYANA",
    "area": "Urban"
  },
  {
    "name": "Jyotsna kumari",
    "father_name": "",
    "mobile": "9001001980",
    "id_type": "",
    "id_number": "",
    "aadhar": "413405480929",
    "age": "35",
    "gender": "Female",
    "address": "Kgh",
    "district": "VISAKHAPATANAM",
    "pincode": "530001",
    "state": "ANDHRA PRADESH",
    "area": "Urban"
  },
  {
    "name": "Najebul",
    "father_name": "",
    "mobile": "9324023992",
    "id_type": "",
    "id_number": "",
    "aadhar": "399302257644",
    "age": "46",
    "gender": "Male",
    "address": "KHARAGRAM TALASHWAR MALDA W B",
    "district": "MALDAH",
    "pincode": "732125",
    "state": "WEST BENGAL",
    "area": "Urban"
  },
  {
    "name": "PRIYADHARSHINI",
    "father_name": "",
    "mobile": "8508596049",
    "id_type": "",
    "id_number": "",
    "aadhar": "373950574570",
    "age": "25",
    "gender": "Female",
    "address": "2 6 AYYAMPALAYAM",
    "district": "COIMBATORE",
    "pincode": "642005",
    "state": "TAMIL NADU",
    "area": ""
  },
  {
    "name": "POONAM DEVI",
    "father_name": "",
    "mobile": "9610424387",
    "id_type": "",
    "id_number": "",
    "aadhar": "979473030735",
    "age": "40",
    "gender": "Female",
    "address": "NARNAUL NARNAUL",
    "district": "MAHENDRAGARH",
    "pincode": "",
    "state": "HARYANA",
    "area": ""
  },
  {
    "name": "S NANDA KUMAR",
    "father_name": "",
    "mobile": "7007864375",
    "id_type": "",
    "id_number": "",
    "aadhar": "553721626056",
    "age": "33",
    "gender": "Male",
    "address": "12-BLOCK 217  LODHI COLONY",
    "district": "SOUTH",
    "pincode": "",
    "state": "DELHI",
    "area": ""
  },
  {
    "name": "Ms  WALESA FERNANDES",
    "father_name": "",
    "mobile": "9819096083",
    "id_type": "",
    "id_number": "",
    "aadhar": "255670155693",
    "age": "39",
    "gender": "Female",
    "address": "203 SUNRAYS ROADS HIRANANDANI ESTATE GHODBUNDER RD THANE",
    "district": "THANE",
    "pincode": "400607",
    "state": "MAHARASHTRA",
    "area": ""
  },
  {
    "name": "SHINIWES",
    "father_name": "",
    "mobile": "7408912173",
    "id_type": "",
    "id_number": "",
    "aadhar": "930065117386",
    "age": "43",
    "gender": "Male",
    "address": "CHHITANI JUNGAL",
    "district": "HARIDWAR",
    "pincode": "",
    "state": "UTTARAKHAND",
    "area": ""
  },
  {
    "name": "SUBHAJIT MONDAL",
    "father_name": "",
    "mobile": "8910788179",
    "id_type": "",
    "id_number": "",
    "aadhar": "921634440277",
    "age": "22",
    "gender": "Male",
    "address": "TORANAGALLU STATION SANDUR TQ BALLARI",
    "district": "BALLARI",
    "pincode": "",
    "state": "KARNATAKA",
    "area": ""
  },
  {
    "name": "Rakesh Kumar",
    "father_name": "",
    "mobile": "9833699586",
    "id_type": "",
    "id_number": "",
    "aadhar": "972960381553",
    "age": "42",
    "gender": "Male",
    "address": "125 MHATRE HOUSE ERANGLE VILLAGE MADH",
    "district": "MUMBAI",
    "pincode": "400061",
    "state": "MAHARASHTRA",
    "area": "Urban"
  },
  {
    "name": "U  Sambasivaiah",
    "father_name": "",
    "mobile": "6305103089",
    "id_type": "",
    "id_number": "",
    "aadhar": "955122816081",
    "age": "45",
    "gender": "Male",
    "address": "Besta Palli",
    "district": "Y S R",
    "pincode": "516214",
    "state": "ANDHRA PRADESH",
    "area": "Chinnamandem"
  },
  {
    "name": "MAITRAYEE KALITA",
    "father_name": "",
    "mobile": "6026689676",
    "id_type": "",
    "id_number": "",
    "aadhar": "735536552275",
    "age": "14",
    "gender": "Female",
    "address": "DATALPARA   NATUN BASTI   H NO 61",
    "district": "KAMRUP METRO",
    "pincode": "",
    "state": "ASSAM",
    "area": ""
  },
  {
    "name": "GARGI",
    "father_name": "",
    "mobile": "8059821624",
    "id_type": "",
    "id_number": "",
    "aadhar": "726624727229",
    "age": "11",
    "gender": "Female",
    "address": "GOVT SCHOOL SHILARPUR",
    "district": "MAHENDRAGARH",
    "pincode": "",
    "state": "HARYANA",
    "area": ""
  },
  {
    "name": "Master ATHARVA KUMAR",
    "father_name": "",
    "mobile": "9004211206",
    "id_type": "",
    "id_number": "",
    "aadhar": "562261394216",
    "age": "13",
    "gender": "Male",
    "address": "G3  202   HAPPU HOME HEIGHST   POONAM GARDEN   MIRA ROAD EAST",
    "district": "MUMBAI",
    "pincode": "401107",
    "state": "MAHARASHTRA",
    "area": "Urban"
  },
  {
    "name": "Bishal Senapati",
    "father_name": "",
    "mobile": "8697231632",
    "id_type": "",
    "id_number": "",
    "aadhar": "420637914150",
    "age": "26",
    "gender": "Male",
    "address": "57 58 santosh roy road barisha 24th paragana pin 700008",
    "district": "KOLKATA",
    "pincode": "700008",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "Ajay Kumar",
    "father_name": "",
    "mobile": "9899616502",
    "id_type": "AADHAR CARD",
    "id_number": "",
    "aadhar": "821580231463",
    "age": "44",
    "gender": "Male",
    "address": "HNO-1069",
    "district": "GHAZIABAD",
    "pincode": "",
    "state": "UTTAR PRADESH",
    "area": ""
  },
  {
    "name": "RATISH PAIKAR",
    "father_name": "",
    "mobile": "9049070552",
    "id_type": "",
    "id_number": "",
    "aadhar": "781405425398",
    "age": "28",
    "gender": "Male",
    "address": "H NO 491A PAL WADA SAVOI VEREM PONDA NORTH GOA - 403401",
    "district": "SOUTH GOA",
    "pincode": "403401",
    "state": "GOA",
    "area": ""
  },
  {
    "name": "SHATAKSHI TYAGI",
    "father_name": "",
    "mobile": "9582123630",
    "id_type": "",
    "id_number": "",
    "aadhar": "255072154997",
    "age": "29",
    "gender": "Female",
    "address": "H NO-410  SEC 21 A  FARIDABAD-121012",
    "district": "FARIDABAD",
    "pincode": "121012",
    "state": "HARYANA",
    "area": ""
  },
  {
    "name": "AJAY SHARMA",
    "father_name": "",
    "mobile": "9911366570",
    "id_type": "",
    "id_number": "",
    "aadhar": "648565295394",
    "age": "58",
    "gender": "Male",
    "address": "A16 MBR ENCLAVE SECTOR 23 DWARKA DELHI",
    "district": "WEST",
    "pincode": "110075",
    "state": "DELHI",
    "area": "Urban"
  },
  {
    "name": "Jaganath H Jagtap",
    "father_name": "",
    "mobile": "9503810144",
    "id_type": "",
    "id_number": "",
    "aadhar": "238149462308",
    "age": "75",
    "gender": "Male",
    "address": "bhalawani",
    "district": "SOLAPUR",
    "pincode": "413101",
    "state": "MAHARASHTRA",
    "area": "Rural"
  },
  {
    "name": "Gowri Naidu",
    "father_name": "",
    "mobile": "7337259694",
    "id_type": "",
    "id_number": "",
    "aadhar": "683608981383",
    "age": "64",
    "gender": "Male",
    "address": "Dsirlam",
    "district": "VIZIANAGARAM",
    "pincode": "535547",
    "state": "ANDHRA PRADESH",
    "area": "Makkuva"
  },
  {
    "name": "MADONVBEI SALOISANEI",
    "father_name": "",
    "mobile": "8415061828",
    "id_type": "",
    "id_number": "",
    "aadhar": "276294703486",
    "age": "27",
    "gender": "Female",
    "address": "HOTEL NANDAN",
    "district": "KAMRUP METRO",
    "pincode": "",
    "state": "ASSAM",
    "area": ""
  },
  {
    "name": "JITENDRA",
    "father_name": "",
    "mobile": "9528040270",
    "id_type": "",
    "id_number": "",
    "aadhar": "448276274402",
    "age": "21",
    "gender": "Male",
    "address": "CO RAGHUVEER RO MUNIMPUR SHARIF NAGAR MORADABAD U P",
    "district": "HARIDWAR",
    "pincode": "",
    "state": "UTTARAKHAND",
    "area": ""
  },
  {
    "name": "NANDITA BARMAN",
    "father_name": "",
    "mobile": "8637362453",
    "id_type": "",
    "id_number": "",
    "aadhar": "653512426336",
    "age": "10",
    "gender": "Female",
    "address": "EAST SITAI   SITAI HAT",
    "district": "COOCHBEHAR",
    "pincode": "736167",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "M Visweswara Rao",
    "father_name": "",
    "mobile": "8688570850",
    "id_type": "",
    "id_number": "",
    "aadhar": "673744468225",
    "age": "19",
    "gender": "Male",
    "address": "Ravivalasa",
    "district": "SRIKAKULAM",
    "pincode": "532212",
    "state": "ANDHRA PRADESH",
    "area": "Tekkali"
  },
  {
    "name": "PARMAR DAMYANTIBEN RATILAL",
    "father_name": "",
    "mobile": "9978258561",
    "id_type": "",
    "id_number": "",
    "aadhar": "364892279695",
    "age": "53",
    "gender": "Female",
    "address": "17 SATYAM NAGAR SOC TEN SURAT",
    "district": "SURAT",
    "pincode": "",
    "state": "GUJARAT",
    "area": "Urban"
  },
  {
    "name": "Gudise  Urukundu",
    "father_name": "",
    "mobile": "6281923366",
    "id_type": "",
    "id_number": "",
    "aadhar": "636591856898",
    "age": "24",
    "gender": "Male",
    "address": "Rachumari",
    "district": "KURNOOL",
    "pincode": "518319",
    "state": "ANDHRA PRADESH",
    "area": "Mantralayam"
  },
  {
    "name": "MASKE GORKHNATH",
    "father_name": "TULSHIRAM",
    "mobile": "7820938972",
    "id_type": "",
    "id_number": "",
    "aadhar": "837958065648",
    "age": "35",
    "gender": "Male",
    "address": "At post S o Tulshiram Maske  At   Sarola  Post Karepur Tq  Renapur Dist Latur",
    "district": "LATUR",
    "pincode": "431522",
    "state": "MAHARASHTRA",
    "area": "Rural"
  },
  {
    "name": "U  Janakiramudu",
    "father_name": "",
    "mobile": "7075373503",
    "id_type": "",
    "id_number": "",
    "aadhar": "325228485408",
    "age": "27",
    "gender": "Male",
    "address": "Gargeyapuram",
    "district": "KURNOOL",
    "pincode": "518452",
    "state": "ANDHRA PRADESH",
    "area": "Kurnool"
  },
  {
    "name": "HARISHCHANDRA PRAJAPATI",
    "father_name": "",
    "mobile": "8604646926",
    "id_type": "",
    "id_number": "",
    "aadhar": "123456789123",
    "age": "42",
    "gender": "Male",
    "address": "JIYA MANSION CHAWL ROOM NO 145 SENAPATI BAPAT MARG PRABHADDEVI MUMBAI 400012",
    "district": "MUMBAI",
    "pincode": "400012",
    "state": "MAHARASHTRA",
    "area": ""
  },
  {
    "name": "P Supriya",
    "father_name": "",
    "mobile": "9701201620",
    "id_type": "",
    "id_number": "",
    "aadhar": "875155546394",
    "age": "32",
    "gender": "Female",
    "address": "Bomminampadu",
    "district": "KRISHNA",
    "pincode": "521343",
    "state": "ANDHRA PRADESH",
    "area": "Mudinepalle"
  },
  {
    "name": "DIWAN SINGH",
    "father_name": "",
    "mobile": "7668659061",
    "id_type": "",
    "id_number": "",
    "aadhar": "595413723794",
    "age": "70",
    "gender": "Male",
    "address": "NANITAL UTTRAKHAND",
    "district": "DEHRADUN",
    "pincode": "",
    "state": "UTTARAKHAND",
    "area": ""
  },
  {
    "name": "PURVA MANE",
    "father_name": "",
    "mobile": "9867201385",
    "id_type": "",
    "id_number": "",
    "aadhar": "273408919518",
    "age": "29",
    "gender": "Female",
    "address": "19 2 AMRUTYOG OPP MANISHA NAGAR GATE NO 2",
    "district": "MUMBAI",
    "pincode": "400082",
    "state": "MAHARASHTRA",
    "area": "Urban"
  },
  {
    "name": "KAMALA KANNAN R",
    "father_name": "",
    "mobile": "9840384891",
    "id_type": "",
    "id_number": "",
    "aadhar": "447668374885",
    "age": "67",
    "gender": "Male",
    "address": "NO 10  R E NAGAR WEST  3RD CROSS STREET PORUR",
    "district": "KANCHIPURAM",
    "pincode": "600116",
    "state": "TAMIL NADU",
    "area": ""
  },
  {
    "name": "RASATABI SHEKH KADAR",
    "father_name": "",
    "mobile": "9420759392",
    "id_type": "",
    "id_number": "",
    "aadhar": "489358219240",
    "age": "72",
    "gender": "Female",
    "address": "GALLI BORGAON  KHULTABAD  AURANGABAD",
    "district": "AURANGABAD",
    "pincode": "431103",
    "state": "MAHARASHTRA",
    "area": "Rural"
  },
  {
    "name": "SAVITA TIWARI",
    "father_name": "Abhishek tiwari",
    "mobile": "9015080451",
    "id_type": "",
    "id_number": "",
    "aadhar": "858193826918",
    "age": "29",
    "gender": "Female",
    "address": "JOTIKA SARAI SAGAR FAIZABAD UP",
    "district": "FIROZABAD",
    "pincode": "224161",
    "state": "UTTAR PRADESH",
    "area": ""
  },
  {
    "name": "DHEESHIDHAN",
    "father_name": "",
    "mobile": "9884887242",
    "id_type": "",
    "id_number": "",
    "aadhar": "301692756376",
    "age": "1",
    "gender": "Male",
    "address": "TA 9 VIJAYASHANTHI APP KANDIGAI CHENNAI",
    "district": "CHENGALPATTU",
    "pincode": "600127",
    "state": "TAMIL NADU",
    "area": ""
  },
  {
    "name": "MOSTAFA HOSSAIN",
    "father_name": "",
    "mobile": "9434460601",
    "id_type": "",
    "id_number": "",
    "aadhar": "683399379741",
    "age": "47",
    "gender": "Male",
    "address": "NALAPARA MALIARI MALIANDIGHI",
    "district": "DINAJPUR DAKSHIN",
    "pincode": "733125",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "DAISY SAPRA",
    "father_name": "",
    "mobile": "",
    "id_type": "",
    "id_number": "",
    "aadhar": "628986163424",
    "age": "60",
    "gender": "Female",
    "address": "",
    "district": "NEW DELHI",
    "pincode": "",
    "state": "DELHI",
    "area": ""
  },
  {
    "name": "RENU BAL GOVIND SAHANI",
    "father_name": "",
    "mobile": "8879874621",
    "id_type": "",
    "id_number": "",
    "aadhar": "292328000058",
    "age": "30",
    "gender": "Female",
    "address": "B 24 EWS COLONY TURBHE SEC 24 NEAR BANK OF INDIA",
    "district": "THANE",
    "pincode": "",
    "state": "MAHARASHTRA",
    "area": ""
  },
  {
    "name": "NESHAT AHMAD",
    "father_name": "ayub",
    "mobile": "9871339678",
    "id_type": "",
    "id_number": "",
    "aadhar": "223187238206",
    "age": "55",
    "gender": "Male",
    "address": "NEAR ANAR WALI MASJID LAXMI NAGAR",
    "district": "EAST",
    "pincode": "110092",
    "state": "DELHI",
    "area": ""
  },
  {
    "name": "MANGALA NALAWADE",
    "father_name": "",
    "mobile": "8828539241",
    "id_type": "",
    "id_number": "",
    "aadhar": "596876548129",
    "age": "57",
    "gender": "Female",
    "address": "building no 7  b 118     SATBHAG   MAROL  ANDHERI",
    "district": "MUMBAI SUBURBAN",
    "pincode": "400072",
    "state": "MAHARASHTRA",
    "area": "Urban"
  },
  {
    "name": "B drakshavalli",
    "father_name": "",
    "mobile": "6305398939",
    "id_type": "",
    "id_number": "",
    "aadhar": "366538197437",
    "age": "20",
    "gender": "Female",
    "address": "T gudipadu",
    "district": "KRISHNA",
    "pincode": "521213",
    "state": "ANDHRA PRADESH",
    "area": "Chatrai"
  },
  {
    "name": "R durga",
    "father_name": "",
    "mobile": "9966739446",
    "id_type": "",
    "id_number": "",
    "aadhar": "425827876519",
    "age": "41",
    "gender": "Female",
    "address": "Vijayawada",
    "district": "KRISHNA",
    "pincode": "520015",
    "state": "ANDHRA PRADESH",
    "area": "Vijayawada"
  },
  {
    "name": "AVANI PRAMOD PATIL",
    "father_name": "",
    "mobile": "9922112040",
    "id_type": "",
    "id_number": "",
    "aadhar": "288563089929",
    "age": "8",
    "gender": "Female",
    "address": "NORTH BLOCK STAFF QUATERS 103 SINHGAD COLLEGE CAMPUS VADgaon 411041",
    "district": "PUNE",
    "pincode": "",
    "state": "MAHARASHTRA",
    "area": "Urban"
  },
  {
    "name": "Shabir Ahmad",
    "father_name": "Gh mohd",
    "mobile": "7780972540",
    "id_type": "",
    "id_number": "",
    "aadhar": "Not availabl",
    "age": "31",
    "gender": "Male",
    "address": "Heff",
    "district": "SHOPIAN",
    "pincode": "192303",
    "state": "JAMMU AND KASHMIR",
    "area": "Rural"
  },
  {
    "name": "ALEXANTONY JOHNPETER",
    "father_name": "",
    "mobile": "9884143115",
    "id_type": "P8080895",
    "id_number": "",
    "aadhar": "956307718985",
    "age": "36",
    "gender": "Male",
    "address": "THAIMOOKAMBIGAI NAGAR THADIKOMBU ROAD DINDIGUL",
    "district": "DINDIGUL",
    "pincode": "624004",
    "state": "TAMIL NADU",
    "area": "Urban"
  },
  {
    "name": "Kr  Rajeswari",
    "father_name": "",
    "mobile": "9966037215",
    "id_type": "",
    "id_number": "",
    "aadhar": "501853540232",
    "age": "14",
    "gender": "Female",
    "address": "Nunna",
    "district": "KRISHNA",
    "pincode": "521212",
    "state": "ANDHRA PRADESH",
    "area": "Vijayawada  Rural"
  },
  {
    "name": "BABU SHAIKH",
    "father_name": "",
    "mobile": "9022655079",
    "id_type": "",
    "id_number": "",
    "aadhar": "598554304213",
    "age": "41",
    "gender": "Male",
    "address": "SION CIRCLE  MUMBAI - 400022",
    "district": "MUMBAI",
    "pincode": "",
    "state": "MAHARASHTRA",
    "area": "Urban"
  },
  {
    "name": "KANDHASAMY S",
    "father_name": "",
    "mobile": "9840362757",
    "id_type": "",
    "id_number": "",
    "aadhar": "476499130395",
    "age": "64",
    "gender": "Male",
    "address": "3 16  MURUGATHERU  CHENNIMALAI",
    "district": "ERODE",
    "pincode": "638051",
    "state": "TAMIL NADU",
    "area": ""
  },
  {
    "name": "Rachit Goel",
    "father_name": "",
    "mobile": "8448693461",
    "id_type": "Z5551813",
    "id_number": "",
    "aadhar": "471631867124",
    "age": "31",
    "gender": "Male",
    "address": "357   28 Onkar Nagar B  Tri Nagar  Delhi",
    "district": "NORTH WEST",
    "pincode": "110035",
    "state": "DELHI",
    "area": "Urban"
  },
  {
    "name": "Sarika patil",
    "father_name": "",
    "mobile": "9405182745",
    "id_type": "",
    "id_number": "",
    "aadhar": "877732188420",
    "age": "42",
    "gender": "Female",
    "address": "Dipali nagar",
    "district": "NASHIK",
    "pincode": "",
    "state": "MAHARASHTRA",
    "area": ""
  },
  {
    "name": "rakesh kumar",
    "father_name": "",
    "mobile": "9816260208",
    "id_type": "",
    "id_number": "",
    "aadhar": "874290674434",
    "age": "40",
    "gender": "Male",
    "address": "vill- tholge plo churadhy reh mayar maudi mp",
    "district": "PUNE",
    "pincode": "41102",
    "state": "MAHARASHTRA",
    "area": "Urban"
  },
  {
    "name": "Minaz Hussain",
    "father_name": "",
    "mobile": "9920241522",
    "id_type": "",
    "id_number": "",
    "aadhar": "934524354013",
    "age": "45",
    "gender": "Male",
    "address": "Bundi",
    "district": "BUNDI",
    "pincode": "",
    "state": "RAJASTHAN",
    "area": ""
  },
  {
    "name": "MEENA SANGA",
    "father_name": "",
    "mobile": "7397872739",
    "id_type": "",
    "id_number": "",
    "aadhar": "682243509345",
    "age": "35",
    "gender": "Female",
    "address": "L6 VERNA ELECTRONIC CITY VERNA GOA 403722",
    "district": "SOUTH GOA",
    "pincode": "403722",
    "state": "GOA",
    "area": ""
  },
  {
    "name": "MANOJ MISHRA",
    "father_name": "",
    "mobile": "8108414248",
    "id_type": "",
    "id_number": "",
    "aadhar": "600038004071",
    "age": "38",
    "gender": "Male",
    "address": "MOHAN TULSI VIHAR  4I  HENDREPADA  BADLAPUR WEST",
    "district": "MUMBAI",
    "pincode": "421503",
    "state": "MAHARASHTRA",
    "area": ""
  },
  {
    "name": "RINKU DEVI",
    "father_name": "",
    "mobile": "8092963253",
    "id_type": "",
    "id_number": "",
    "aadhar": "721996418547",
    "age": "26",
    "gender": "Female",
    "address": "JAKHODA BAHADURGARH",
    "district": "JHAJJAR",
    "pincode": "",
    "state": "HARYANA",
    "area": ""
  },
  {
    "name": "A Subrahmanyam Reddy",
    "father_name": "",
    "mobile": "8341700615",
    "id_type": "",
    "id_number": "",
    "aadhar": "780061103632",
    "age": "24",
    "gender": "Male",
    "address": "Bethapudi",
    "district": "GUNTUR",
    "pincode": "522101",
    "state": "ANDHRA PRADESH",
    "area": "Bapatla"
  },
  {
    "name": "Ms  SAYED TANZEEL FATEMA",
    "father_name": "",
    "mobile": "9678797032",
    "id_type": "",
    "id_number": "",
    "aadhar": "976295832244",
    "age": "28",
    "gender": "Female",
    "address": "Ramnast pora jinsi Aurangabad",
    "district": "AURANGABAD",
    "pincode": "431001",
    "state": "MAHARASHTRA",
    "area": ""
  },
  {
    "name": "SANJAY RAI",
    "father_name": "",
    "mobile": "9506704484",
    "id_type": "",
    "id_number": "",
    "aadhar": "452586134485",
    "age": "45",
    "gender": "Male",
    "address": "GADCHANDUR",
    "district": "CHANDRAPUR",
    "pincode": "442908",
    "state": "MAHARASHTRA",
    "area": ""
  },
  {
    "name": "RAJESH KUMAR",
    "father_name": "",
    "mobile": "9319339700",
    "id_type": "",
    "id_number": "",
    "aadhar": "779949107430",
    "age": "37",
    "gender": "Male",
    "address": "H NO 5  VILLAGE MAJRA  TEHSIL SOHNA  GURUGRAM",
    "district": "GURUGRAM",
    "pincode": "122103",
    "state": "HARYANA",
    "area": ""
  },
  {
    "name": "SANTOSH KUMAR",
    "father_name": "",
    "mobile": "6200363976",
    "id_type": "",
    "id_number": "",
    "aadhar": "559768374006",
    "age": "25",
    "gender": "Male",
    "address": "VILLAGE - BANJARI  PO - BANJARI  PS - BARHARWA  DIST - SAHIBGANJ  JHARKHAND",
    "district": "SAHIBGANJ",
    "pincode": "816101",
    "state": "JHARKHAND",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "MOHAMMED  ASHRAF",
    "father_name": "",
    "mobile": "9947464249",
    "id_type": "",
    "id_number": "",
    "aadhar": "762358776029",
    "age": "57",
    "gender": "Male",
    "address": "2 4 99  KARIMNAGAR",
    "district": "KARIMNAGAR",
    "pincode": "505001",
    "state": "TELANGANA",
    "area": ""
  },
  {
    "name": "SIDDHARTHA SANKAR DAS",
    "father_name": "",
    "mobile": "9435011636",
    "id_type": "",
    "id_number": "",
    "aadhar": "993045557533",
    "age": "50",
    "gender": "Male",
    "address": "VILL  KANAKPUR  PO  KANAKPUR  PS  NARAYANGARH  DIST  PASCHIM MEDINIPUR  PIN  721437",
    "district": "PASCHIM MEDINIPUR",
    "pincode": "721437",
    "state": "WEST BENGAL",
    "area": ""
  },
  {
    "name": "PRASHANT K",
    "fathersName": "",
    "phoneNumber": "9820263696",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "824683536998",
    "age": "41",
    "gender": "Male",
    "address": "601 B WING SKY VISTA D N NAGAR",
    "district": "MUMBAI",
    "pincode": "400053",
    "state": "MAHARASHTRA",
    "town": "Urban"
  },
  {
    "name": "MD KASHIM",
    "fathersName": "",
    "phoneNumber": "9315178347",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "870752532282",
    "age": "19",
    "gender": "Male",
    "address": "H NO 337 GALI NO 7 SHAKTI PARK GURGAON",
    "district": "GURUGRAM",
    "pincode": "",
    "state": "HARYANA",
    "town": ""
  },
  {
    "name": "Mr Kiaan Kanade",
    "fathersName": "",
    "phoneNumber": "9819813089",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "301548711277",
    "age": "9",
    "gender": "Male",
    "address": "AHMEDABAD",
    "district": "AHMADABAD",
    "pincode": "",
    "state": "GUJARAT",
    "town": ""
  },
  {
    "name": "My manohar Reddy",
    "fathersName": "",
    "phoneNumber": "7993768617",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "880867937678",
    "age": "20",
    "gender": "Male",
    "address": "Rajapanagalroad",
    "district": "PRAKASAM",
    "pincode": "523001",
    "state": "ANDHRA PRADESH",
    "town": "Ongole"
  },
  {
    "name": "MANICKAM CHINNATHAMPI",
    "fathersName": "",
    "phoneNumber": "9566878444",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "832773103271",
    "age": "36",
    "gender": "Male",
    "address": "13-329-2  5TH STREET  SAMUNDI NAGAR  STEEL PLANT 1ST GATE  SALEM",
    "district": "SALEM",
    "pincode": "636030",
    "state": "TAMIL NADU",
    "town": ""
  },
  {
    "name": "SAIMAHESH PERUMAL",
    "fathersName": "",
    "phoneNumber": "9486215410",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "788246098788",
    "age": "31",
    "gender": "Male",
    "address": "16 PAVENDAR BHARATHIDASAN SCHOOL GANDHI NAGAR POST TIRUPUR",
    "district": "TIRUPPUR",
    "pincode": "",
    "state": "TAMIL NADU",
    "town": ""
  },
  {
    "name": "KUNAL DHAR",
    "fathersName": "",
    "phoneNumber": "9667569642",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "992833680479",
    "age": "16",
    "gender": "Male",
    "address": "B 31 MEA HOUSING COMPLEX RthanksHA KRISHNA MARG CHANKYPURI DELHI NEW DELHI",
    "district": "NEW DELHI",
    "pincode": "110021",
    "state": "DELHI",
    "town": ""
  },
  {
    "name": "Jasleen kaur kainth",
    "fathersName": "",
    "phoneNumber": "9131777143",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "949061990596",
    "age": "14",
    "gender": "Female",
    "address": "Bsp",
    "district": "BILASPUR",
    "pincode": "",
    "state": "CHHATTISGARH",
    "town": ""
  },
  {
    "name": "PRAFULLA KUNDU",
    "fathersName": "",
    "phoneNumber": "8910636097",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "994478079118",
    "age": "69",
    "gender": "Male",
    "address": "OKSS HOTEL THOUSAND LIGHTS CHENNAI",
    "district": "CHENNAI",
    "pincode": "600006",
    "state": "TAMIL NADU",
    "town": ""
  },
  {
    "name": "ARCHANA  CHAVAN",
    "fathersName": "SHAMRAO",
    "phoneNumber": "9561779474",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "509236607092",
    "age": "25",
    "gender": "Male",
    "address": "A P -KULRLA  WEST  MUMBAI  KRANTI  NAGAR  BAIL  BAZAR  MUMBAI",
    "district": "MUMBAI",
    "pincode": "400070",
    "state": "MAHARASHTRA",
    "town": ""
  },
  {
    "name": "Gavara Ramu",
    "fathersName": "",
    "phoneNumber": "7901275735",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "652582426691",
    "age": "42",
    "gender": "Male",
    "address": "K Gumpa",
    "district": "VIZIANAGARAM",
    "pincode": "535524",
    "state": "ANDHRA PRADESH",
    "town": "Komarada"
  },
  {
    "name": "Ch ashok Kumar",
    "fathersName": "",
    "phoneNumber": "9989986893",
    "otherNumber": "",
    "passportNumber": "",
    "aadharNumber": "806890450747",
    "age": "29",
    "gender": "Female",
    "address": "Edepalli",
    "district": "KRISHNA",
    "pincode": "521001",
    "state": "ANDHRA PRADESH",
    "town": "Machilipatnam"
  },
  {
      "name": "Ch ashok Kumar",
      "fathersName": "",
      "phoneNumber": "9989986893",
      "otherNumber": "",
      "passportNumber": "",
      "aadharNumber": "806890450747",
      "age": "29",
      "gender": "Female",
      "address": "Edepalli",
      "district": "KRISHNA",
      "pincode": "521001",
      "state": "ANDHRA PRADESH",
      "town": "Machilipatnam"
    }
  ];

  // Get the phone number from the query string
  const { phone } = req.query;

  // Check if phone number is provided
  if (!phone) {
    return res.status(400).json({ 
      error: 'Phone number is required. Use /api/search?phone=YOUR_NUMBER' 
    });
  }

  // Search for user with the provided phone number
  const user = users.find(u => u.phoneNumber === phone);

  // If user not found
  if (!user) {
    return res.status(404).json({ 
      error: 'User not found with the provided phone number' 
    });
  }

  // Return the user details
  res.status(200).json(user);
}
  
